name: Netcat Port Test

on:
  push:
    branches:
      - main

jobs:
  netcat-port-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Start Go server
        run: |
          nohup go run server.go &
          echo "Waiting for the server to start..."
          sleep 5

      - name: Test server with curl
        run: |
          curl -vz http://localhost:3000
