name: Netcat Port Test

on:
  push:
    branches:
      - main

jobs:
  netcat-port-test:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3

      - name: Open Port with Netcat
        run: |
          nohup nc -4 -l 3000 &

      - name: Wait for Port to Open
        run: sleep 5

      - name: Check Port with Netcat
        run: |
          nc -zv -4 localhost 3000
