name: Port Test

on:
  push:
    branches:
      - main

jobs:
  netcat-port-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Start Go server
        run: |
          go build -o server server.go
          nohup ./server &

          echo "Waiting for the server to start..."
          sleep 5

      - name: Test server
        run: |
          nc -vz localhost 3000

      - name: Show output
        run: |
          echo "Print output..."
          cat nohup.out
